### ISSUE TITLE
Cannot change to jyutping input or view settings after upgrading to 0.16.2

### ISSUE THREAD

**Issue by AmiciA** [rime/rime-cantonese#166]
I recently got a pop-up that a new version of Squirrel was available, so I installed the update, but afterwards I could no longer type in jyutping. I tried re-installing, but I'm not sure if I needed to uninstall first.

Also, when I click on "Settings…" in the keyboard settings menu bar item, it just opens the path `Users/[username]/Library/Rime`. When I view the input sources dialogue, there is also no settings. 
![image](https://user-images.githubusercontent.com/437844/217305191-3e980726-7d5a-46c3-82eb-5f1d6109e529.png)

When I press ``ctrl+```, I see the following options. I _think_  that the jyutping option used to be in there, but it's been a while since I first installed Squirrel, so I can't remember.
![image](https://user-images.githubusercontent.com/437844/217306612-2fd6de2b-006e-4164-b867-f276d7afc5c2.png)

**Environment**
2021 Macbook Pro M1
Ventura 13.1 (22C65)

**Comment by hfhchan** [comment]
Settings 嗰版空係正常嘅
Update 咗 Squirrel 會洗走咗我哋粵拼輸入法啲設定，變咗粵語拼音

目前有兩個解決方法：
一係用安裝包重新安裝，唔使剷走 existing 嗰個輸入法。
二係人手 patch 返啲輸入法設定，請參閲 https://t.me/rime_cantonese/131427

**Comment by hfhchan** [comment]
> 我哋係等緊重新打包？

係，jimmy pack 咗個 0.16.1 嘅 update (最新版可以去 https://github.com/CanCLID/rime-cantonese-installer/actions/runs/4116535701 下載，有個 update 嘅詞庫)，點知轉頭又出過個 0.16.2

**Comment by hfhchan** [comment]
Please download the newest update from [https://github.com/rime/rime-cantonese/releases/tag/2023.02.08](https://github.com/rime/rime-cantonese/releases/tag/2023.02.08).

You do not need to uninstall the old version before installing the new version.
You will be prompted to log out after install. Due to a macOS restriction, Squirrel will not work until you log in again.

You may use "Shift" to toggle between the 中文 mode and ABC mode when Squirrel is selected. Upon first log in, it will take a few seconds for Squirrel to activate correctly.

Please feel free to contact us on [Telegram](https://t.me/rime_cantonese) if you have more problems.

**Comment by lotem** [comment]
> Settings 嗰版空係正常嘅 Update 咗 Squirrel 會洗走咗我哋粵拼輸入法啲設定，變咗粵語拼音
> 
> 目前有兩個解決方法： 一係用安裝包重新安裝，唔使剷走 existing 嗰個輸入法，畀佢提示更新嘅時候記得噉 Skip this update。 二係人手 patch 返啲輸入法設定，請參閲 https://t.me/rime_cantonese/131427

爲什麼不把輸入方案和自定義配置安裝到用戶文件夾呢？

如果修改Squirrel.app的內容，那應該視爲獨立的發行版，軟件更新頻道也許要重建，這樣定製一個方案的開銷太大了。我覺得這種實現方式不可取。

**Comment by hfhchan** [comment]
之後應該會改成安裝在用户資料夾。目前安裝方式無法更新透過 plum 安裝碼表的用户。

**Comment by lotem** [comment]
善哉
